# Generated by Django 4.1.7 on 2023-06-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0004_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='imagelq',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
