# Generated by Django 4.1.7 on 2023-06-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0005_painting_imagelq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='imagelq',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
