# Generated by Django 4.1.7 on 2023-06-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0006_alter_painting_imagelq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='imagelq',
            field=models.ImageField(upload_to=''),
        ),
    ]
