# Generated by Django 4.1.5 on 2023-06-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0006_alter_avatar_avt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avt',
            field=models.ImageField(default='https://cdn-icons-png.flaticon.com/512/149/149071.png', upload_to=''),
        ),
    ]
