# Generated by Django 4.1.5 on 2023-06-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0007_alter_avatar_avt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avt',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
