# Generated by Django 4.1.7 on 2023-06-10 14:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0007_alter_painting_imagelq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
